// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/clients/ec2_client.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	common "github.com/ydataai/aws-adapter/pkg/common"
)

// MockEC2ClientInterface is a mock of EC2ClientInterface interface.
type MockEC2ClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockEC2ClientInterfaceMockRecorder
}

// MockEC2ClientInterfaceMockRecorder is the mock recorder for MockEC2ClientInterface.
type MockEC2ClientInterfaceMockRecorder struct {
	mock *MockEC2ClientInterface
}

// NewMockEC2ClientInterface creates a new mock instance.
func NewMockEC2ClientInterface(ctrl *gomock.Controller) *MockEC2ClientInterface {
	mock := &MockEC2ClientInterface{ctrl: ctrl}
	mock.recorder = &MockEC2ClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEC2ClientInterface) EXPECT() *MockEC2ClientInterfaceMockRecorder {
	return m.recorder
}

// GetGPUInstances mocks base method.
func (m *MockEC2ClientInterface) GetGPUInstances(arg0 string) (common.GPU, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGPUInstances", arg0)
	ret0, _ := ret[0].(common.GPU)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGPUInstances indicates an expected call of GetGPUInstances.
func (mr *MockEC2ClientInterfaceMockRecorder) GetGPUInstances(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGPUInstances", reflect.TypeOf((*MockEC2ClientInterface)(nil).GetGPUInstances), arg0)
}
