// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/clients/service_quota_client.go

// Package mock is a generated GoMock package.
package mock

import (
	"context"
	"reflect"

	"github.com/golang/mock/gomock"
)

// MockServiceQuotaClientInterface is a mock of ServiceQuotaClientInterface interface.
type MockServiceQuotaClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceQuotaClientInterfaceMockRecorder
}

// MockServiceQuotaClientInterfaceMockRecorder is the mock recorder for MockServiceQuotaClientInterface.
type MockServiceQuotaClientInterfaceMockRecorder struct {
	mock *MockServiceQuotaClientInterface
}

// NewMockServiceQuotaClientInterface creates a new mock instance.
func NewMockServiceQuotaClientInterface(ctrl *gomock.Controller) *MockServiceQuotaClientInterface {
	mock := &MockServiceQuotaClientInterface{ctrl: ctrl}
	mock.recorder = &MockServiceQuotaClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceQuotaClientInterface) EXPECT() *MockServiceQuotaClientInterfaceMockRecorder {
	return m.recorder
}

// GetAvailableGPUInstances mocks base method.
func (m *MockServiceQuotaClientInterface) GetAvailableQuota(ctx context.Context, arg0, arg1 string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableGPUInstances", ctx, arg0, arg1)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableGPUInstances indicates an expected call of GetAvailableGPUInstances.
func (mr *MockServiceQuotaClientInterfaceMockRecorder) GetAvailableQuota(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableGPUInstances", reflect.TypeOf((*MockServiceQuotaClientInterface)(nil).GetAvailableQuota), arg0, arg1, arg2)
}
